# Concepts

## The None (newaxis)

https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis

In [8]:
import numpy as np 

x = np.arange(3)
print(x, x.shape)

a = x[:, np.newaxis]
print(a, a.shape)

b = x[None, :]
print(b, b.shape)

c = x[np.newaxis, np.newaxis, :]
print(c, c.shape)

d = x[None, np.newaxis, :, None]
print(d, d.shape)

[0 1 2] (3,)
[[0]
 [1]
 [2]] (3, 1)
[[0 1 2]] (1, 3)
[[[0 1 2]]] (1, 1, 3)
[[[[0]
   [1]
   [2]]]] (1, 1, 3, 1)


## Broadcast

* https://numpy.org/doc/stable//user/basics.broadcasting.html
* https://juansensio.com/blog/008_numpy_aop

### Compatibility

Two dimensions are compatible when

- they are equal, or
- one of them is 1.

In [17]:
import numpy as np

a = np.array([[1]])
b = np.array([2.0, 4.0, 6.0])
broad =  b * a
print(a, b, a.shape, b.shape, broad, broad.shape)


# Error operands could not be broadcast together with shapes (1,2) (3,)
a = np.array([[1, 2]])
b = np.array([2.0, 4.0, 6.0])
#broad = a * b
#a, b, a.shape, b.shape, broad, broad.shape

a = np.array([[1, 2, 3, 4]])
b = np.array([2.0, 4.0, 6.0]) # The broadcast will fail Error "operands could not be broadcast together with shapes (1,4) (3,)"
# To fix we can add an index 
b = b[:, None]
print("shapes->", a, b, a.shape, b.shape)
broad = a * b
broad, broad.shape

[[1]] [2. 4. 6.] (1, 1) (3,) [[2. 4. 6.]] (1, 3)
shapes-> [[1 2 3 4]] [[2.]
 [4.]
 [6.]] (1, 4) (3, 1)


(array([[ 2.,  4.,  6.,  8.],
        [ 4.,  8., 12., 16.],
        [ 6., 12., 18., 24.]]),
 (3, 4))

In [ ]:
A = np.array([[0, 1, 2],
             [3, 4, 5]])
B = np.array([[100],
       [200]])
sum = A + B

A,B, A.shape, B.shape, sum, sum.shape

In [ ]:
C = np.array([100, 200, 300])
C.shape

sum = A + C



A,C, A.shape, C.shape, sum, sum.shape