# Info

NumPy Tutorial (2022): For Physicists, Engineers, and Mathematicians
https://www.youtube.com/watch?v=DcfYgePyedM

https://pythonguides.com/convert-pandas-dataframe-to-numpy-array/

Introduction to Numerical Computing with NumPy | SciPy 2019 Tutorial | Alex Chabot-Leclerc https://www.youtube.com/watch?v=ZB7BZMhfPgk

In [ ]:
import open3d as o3d
import numpy as np
np.set_printoptions(precision=4)
import matplotlib.pyplot as plt
from skimage import measure

In [ ]:
m = o3d.geometry.TriangleMesh.create_sphere(radius=1.0, resolution=10)

In [ ]:
m

In [ ]:
verts = np.asarray(m.vertices)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
plt.plot(verts[:,0], verts[:,1], verts[:,2], "o",  alpha=1)
plt.show()

In [ ]:
verts, verts.shape, verts.ndim

In [ ]:
x = verts.reshape(2,-1,3)

In [ ]:
x.shape, x.ndim

In [ ]:
x

In [ ]:
verts, faces, normals, values = measure.marching_cubes(x, 0)

In [ ]:
verts, verts.shape, verts.ndim

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
plt.plot(verts[:,0], verts[:,1], verts[:,2], "o",  alpha=1)
plt.show()

In [ ]:
x, y, z = np.mgrid[verts[:,0],
                       verts[:,1],
                       verts[:,2]]

In [ ]:
import mcubes
mcubes.export_obj(verts, faces, 'mesh.obj')

In [ ]:
mesh = o3d.io.read_triangle_mesh("mesh.obj")
o3d.visualization.draw_geometries([mesh])

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(0,4,5)
y = np.linspace(6,10,5)
z = np.linspace(0,1,10)

In [ ]:
xv, yv = np.meshgrid(x,y)

In [ ]:
xv, yv , zv= np.meshgrid(x,y,z)

In [ ]:
xv, yv

In [ ]:
#zv = xv**2 + yv*2
zv = xv**0 + yv*0

In [ ]:
zv

In [ ]:
plt.contourf(xv,yv,zv,levels=20)

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(xv,yv,zv, cmap="plasma", linewidth=0, antialiased=False, alpha=0.5)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z');
# rotation
ax.view_init(45,70)
plt.show()

In [ ]:
import plotly.graph_objects as go
import numpy as np

y = np.linspace(1,90,90)
#y = np.zeros([15,6])

z1 = np.array([
    [8.83,8.89,8.81,8.87,8.9,8.87],
    [8.89,8.94,8.85,8.94,8.96,8.92],
    [8.84,8.9,8.82,8.92,8.93,8.91],
    [8.79,8.85,8.79,8.9,8.94,8.92],
    [8.79,8.88,8.81,8.9,8.95,8.92],
    [8.8,8.82,8.78,8.91,8.94,8.92],
    [8.75,8.78,8.77,8.91,8.95,8.92],
    [8.8,8.8,8.77,8.91,8.95,8.94],
    [8.74,8.81,8.76,8.93,8.98,8.99],
    [8.89,8.99,8.92,9.1,9.13,9.11],
    [8.97,8.97,8.91,9.09,9.11,9.11],
    [9.04,9.08,9.05,9.25,9.28,9.27],
    [9,9.01,9,9.2,9.23,9.2],
    [8.99,8.99,8.98,9.18,9.2,9.19],
    [8.93,8.97,8.97,9.18,9.2,9.18]
])



In [ ]:
z1.shape, z1.size, z1.ndim

In [ ]:
yv = 

In [ ]:
fig = go.Figure(data=[
    go.Surface(z=z1, y=y)
])

fig.show()

In [ ]:
xv

In [ ]:
yv

In [ ]:
#zv = np.log(xv+yv)
plt.contourf(xv,yv,zv, levels=30)
plt.colorbar()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

from skimage import measure
from skimage.draw import ellipsoid


# Generate a level set about zero of two identical ellipsoids in 3D
ellip_base = ellipsoid(6, 10, 16, levelset=True)



In [ ]:
ellip_base, ellip_base.shape, ellip_base.ndim

In [ ]:
# Use marching cubes to obtain the surface mesh of these ellipsoids
verts, faces, normals, values = measure.marching_cubes(ellip_double, 0)

In [ ]:
X = np.linspace(1,4,4)

In [ ]:
x

In [ ]:
import numpy as np

In [ ]:
import numpy as np
jugadores = np.ones(10)*2500

In [ ]:
jugadores

In [ ]:
65000/2 - jugadores.sum()

In [ ]:
import numpy as np
 
# array = geek.arrange(8)
# The 'numpy' module has no attribute 'arrange'
array1 = geek.arange(8)
print("Original array : \n", array1)
 
# shape array with 2 rows and 4 columns
array2 = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n",
      array2)
 
# shape array with 4 rows and 2 columns
array3 = geek.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n",
      array3, array3.shape, array3.ndim)
 
# Constructs 3D array
array4 = geek.arange(9).reshape(3, 1, 3)
print("\nOriginal array reshaped to 3D : \n",
      array4, array4.shape, array4.ndim)

In [ ]:
n = np.mgrid[10:15, 10:15]

In [ ]:
n.size, n.shape, n.ndim

In [ ]:
n

# NPZ files

In [ ]:
from numpy import load
# load dict of arrays
dict_data = load('mnist.npz')


In [ ]:
for k in dict_data.files:
    print(k)

In [ ]:
# extract the first array
data = dict_data['arr_0']
# print the array
print(data)

In [ ]:
b = geek.load('x_train.npy')

In [ ]:
b

# 3d cube 

In [ ]:
from numpy import arange, meshgrid

x = arange(7)
y = arange(0,30,10)
z = arange(0,200,100)
ym, zm, xm = meshgrid(y, z, x)
cube = xm + ym + zm

var = xm

print(var.shape, var.ndim, var.size, var)

print(cube.shape, cube.size, cube.ndim, cube)

In [2]:
import numpy as np
x = np.array((1,2,3))

In [4]:
x.shape, type(x), x.ndim

((3,), numpy.ndarray, 1)

In [5]:
# generate some neat n times 3 matrix using a variant of sync function
x = np.linspace(-3, 3, 401)
mesh_x, mesh_y = np.meshgrid(x, x)
z = np.sinc((np.power(mesh_x, 2) + np.power(mesh_y, 2)))
z_norm = (z - z.min()) / (z.max() - z.min())
xyz = np.zeros((np.size(mesh_x), 3))
xyz[:, 0] = np.reshape(mesh_x, -1)
xyz[:, 1] = np.reshape(mesh_y, -1)
xyz[:, 2] = np.reshape(z_norm, -1)
print('xyz')
print(xyz)

xyz
[[-3.         -3.          0.17846472]
 [-2.985      -3.          0.17440115]
 [-2.97       -3.          0.17063709]
 ...
 [ 2.97        3.          0.17063709]
 [ 2.985       3.          0.17440115]
 [ 3.          3.          0.17846472]]


In [7]:
mesh_x.shape, mesh_x.ndim, mesh_x.size, mesh_x

((401, 401),
 2,
 160801,
 array([[-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        ...,
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ]]))

In [8]:
mesh_x.shape, mesh_x.ndim, mesh_x.size, mesh_x

((401, 401),
 2,
 160801,
 array([[-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        ...,
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ],
        [-3.   , -2.985, -2.97 , ...,  2.97 ,  2.985,  3.   ]]))