In [31]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

from skimage import measure
from skimage.draw import ellipsoid


# Generate a level set about zero of two identical ellipsoids in 3D
ellip_base = ellipsoid(6, 10, 16, levelset=True)
ellip_double = np.concatenate((ellip_base[:-1, ...],
                               ellip_base[2:, ...]), axis=0)

print(type(ellip_base), ellip_base.shape, ellip_base.ndim, ellip_base.size, ellip_base)

#X, Y, Z = np.mgrid[:20, :20, :20]
#u = (X-10)**2 + (Y-10)**2 + (Z-10)**2 - 8**2

# Use marching cubes to obtain the surface mesh of these ellipsoids
#verts, faces, normals, values = measure.marching_cubes(u, 0)

# Use marching cubes to obtain the surface mesh of these ellipsoids
verts, faces, normals, values = measure.marching_cubes_classic(ellip_double, 0)

# Display resulting triangular mesh using Matplotlib. This can also be done
# with mayavi (see skimage.measure.marching_cubes docstring).
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')

# Fancy indexing: `verts[faces]` to generate a collection of triangles
mesh = Poly3DCollection(verts[faces])
mesh.set_edgecolor('k')
ax.add_collection3d(mesh)

ax.set_xlabel("x-axis: a = 6 per ellipsoid")
ax.set_ylabel("y-axis: b = 10")
ax.set_zlabel("z-axis: c = 16")

ax.set_xlim(0, X.shape[0])  # a = 6 (times two for 2nd ellipsoid)
ax.set_ylim(0, X.shape[1])  # b = 10
ax.set_zlim(0, X.shape[2])  # c = 16

plt.tight_layout()
plt.show()

<class 'numpy.ndarray'> (15, 23, 35) 3 12075 [[[2.70001736 2.57111111 2.45001736 ... 2.45001736 2.57111111 2.70001736]
  [2.49001736 2.36111111 2.24001736 ... 2.24001736 2.36111111 2.49001736]
  [2.30001736 2.17111111 2.05001736 ... 2.05001736 2.17111111 2.30001736]
  ...
  [2.30001736 2.17111111 2.05001736 ... 2.05001736 2.17111111 2.30001736]
  [2.49001736 2.36111111 2.24001736 ... 2.24001736 2.36111111 2.49001736]
  [2.70001736 2.57111111 2.45001736 ... 2.45001736 2.57111111 2.70001736]]

 [[2.33890625 2.21       2.08890625 ... 2.08890625 2.21       2.33890625]
  [2.12890625 2.         1.87890625 ... 1.87890625 2.         2.12890625]
  [1.93890625 1.81       1.68890625 ... 1.68890625 1.81       1.93890625]
  ...
  [1.93890625 1.81       1.68890625 ... 1.68890625 1.81       1.93890625]
  [2.12890625 2.         1.87890625 ... 1.87890625 2.         2.12890625]
  [2.33890625 2.21       2.08890625 ... 2.08890625 2.21       2.33890625]]

 [[2.03335069 1.90444444 1.78335069 ... 1.78335069 

AttributeError: module 'skimage.measure' has no attribute 'marching_cubes_classic'

In [8]:
ellip_base.shape

(15, 23, 35)

In [21]:
ellip_base[:-1, ...].shape

(14, 23, 35)

In [22]:
ellip_base[2:, ...].shape

(13, 23, 35)

In [26]:
np.concatenate((ellip_base[:-1, ...],
                               ellip_base[2:, ...]), axis=0).shape

(27, 23, 35)